USE codeup_test_db;

INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller',1982 ,70 , 'Pop, post-disco, funk, rock'),
       ('AC/DC', 'Back in Black',1980 ,50 , 'Hard rock'),
       ('Whitney Houston / various artists', 'The Bodyguard',1992 ,45 , 'R&B, soul, pop, soundtrack'),
       ('Eagles', 'Their Greatest Hits (1971–1975)',1976 ,44 , 'Country rock, soft rock, folk rock'),
       ('Pink Floyd', 'The Dark Side of the Moon',1973 ,44 , 'Progressive rock'),
       ('Eagles', 'Hotel California',1976 ,42 , 'Soft rock'),
       ('Shania Twain', 'Come On Over',1997 ,40 , 'Country, pop'),
       ('Fleetwood Mac', 'Rumours',1977 ,40 , 'Soft rock'),
       ('Bee Gees / Various artists', 'Saturday Night Fever',1977 ,40 , 'Disco'),

       ('Various artists', 'Grease: The Original Soundtrack from the Motion Picture',1978 ,38 , 'Rock and roll'),
       ('Led Zeppelin', 'Led Zeppelin IV',1971 ,37 , 'Hard rock, heavy metal, folk rock'),
       ('Michael Jackson', 'Bad',1987 ,35 , 'Pop, rhythm and blues, funk and rock'),
       ('Alanis Morissette', 'Jagged Little Pill',1995 ,33 , 'Alternative rock'),
       ('Celine Dion', 'Falling into You',1996 ,32 , 'Pop, soft rock'),
       ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band',1967 ,32 , 'Rock'),
       ('Various artists', 'Dirty Dancing',1987 ,32 , 'Pop, rock, R&B'),
       ('Michael Jackson', 'Dangerous',1991 ,32 , 'New jack swing, R&B and pop'),
       ('Adele', '21',2011 ,31 , 'Pop, soul'),
       ('The Beatles', '1',2000 ,31 , 'Rock'),
       ('Metallica', 'Metallica',1991 ,31 , 'Heavy metal'),
       ('Celine Dion', 'Let''s Talk About Love',1997 ,31 , 'Pop, soft rock'),
       ('The Beatles', 'Abbey Road',1969 ,31 , 'Rock'),
       ('Guns N'' Roses', 'Appetite for Destruction',1987 ,30 , 'Hard rock'),
       ('Bruce Springsteen', 'Born in the U.S.A.',1984 ,30 , 'Heartland rock'),
       ('Meat Loaf', 'Bat Out of Hell',1977 ,30 , 'Hard rock, glam rock, progressive rock'),
       ('ABBA', 'Gold: Greatest Hits',1992 ,30 , 'Pop, disco'),
       ('Dire Straits', 'Brothers in Arms',1985 ,30 , '	Roots rock, blues rock, soft rock'),
       ('Santana', 'Supernatural',1999 ,30 , 'Latin rock'),
       ('Madonna', 'The Immaculate Collection',1990 ,30 , 'Pop, dance'),
       ('Pink Floyd', 'The Wall',1979 ,30 , 'Progressive rock'),
       ('James Horner', 'Titanic: Music from the Motion Picture',1997 ,30 , 'Film score'),
       ('Nirvana', 'Nevermind',1991 ,30 , 'Grunge, alternative rock');